# Generated by Django 5.1 on 2024-09-02 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0002_ticket_booking_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenFeature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.feature')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.screen')),
            ],
            options={
                'unique_together': {('screen', 'feature')},
            },
        ),
    ]
