# Generated by Django 5.1 on 2024-09-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0004_seat_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking_status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], max_length=100),
        ),
    ]
