# Generated by Django 5.1 on 2024-09-10 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0005_alter_ticket_booking_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScreenFeature',
        ),
    ]
